
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('episodes').del()
    .then(() =>
      // Inserts seed entries
      knex('episodes').insert([
        { 
          episode_title: 'Pilot',
          season: 1,
          episode_number: 1,
          episode_length: '23:00 min',
          release_date: 'September 24, 2007',
          interesting_fact: 'An unaired pilot exist. Also, the scene where Sheldon and Leonard observe Penny through her open apartment door would be repeated as an homage in the series 100th episode. The characters would even be dressed similarly, right down to Penny wearing the exact same blue top that she wears here.',
          image: 'www.justwatch.com/images/backdrop/458881/s1440/the-big-bang-theory',
        },
        { 
          episode_title: 'The Big Bran Hypothesis”',
          season: 1,
          episode_number: 2,
          episode_length: '21:00 min',
          release_date: 'October 1, 2007',
          interesting_fact: 'The title refers to the cereals that Sheldon stores on top of the refrigerator, sorted by fiber content, specifically the highest fiber cereal, "Big Bran"',
          image: 'www.justwatch.com/images/backdrop/458881/s1440/the-big-bang-theory',
        },
        { 
          episode_title: 'The Fuzzy Boots Corollary',
          season: 1,
          episode_number: 3,
          episode_length: '22:00 min',
          release_date: 'October 8, 2007',
          interesting_fact: 'Title reference: One of the names that Leonard was considering for his cat.',
          image: 'www.justwatch.com/images/backdrop/458881/s1440/the-big-bang-theory',
        },
        { 
          episode_title: 'The Luminous Fish',
          season: 1,
          episode_number: 4,
          episode_length: '21:00 min',
          release_date: 'October 15, 2007',
          interesting_fact: 'It is revealed here that Sheldon\'s father is dead, as well as Parsons\'s father.',
          image: '/www.justwatch.com/images/backdrop/458881/s1440/the-big-bang-theory',
        },
        { 
          episode_title: 'The Hamburger Postulate',
          season: 1,
          episode_number: 5,
          episode_length: '20:25 min',
          release_date: 'October 22, 2007',
          interesting_fact: 'Sheldon\'s door-knocking OCD (I.e."Penny, Penny, Penny") doesn\'t manifest when he knocks on Penny\'s door after seeing a tie on Leonard\'s room door-knob.',
          image: '/www.justwatch.com/images/backdrop/458881/s1440/the-big-bang-theory',
        },
        { 
          episode_title: 'The Middle Earth Paradigm',
          season: 1,
          episode_number: 6,
          episode_length: '21:33 min',
          release_date: 'October 26, 2007',
          interesting_fact: '“Season 1\'s highest rated episode.',
          image: '/www.justwatch.com/images/backdrop/458881/s1440/the-big-bang-theory',
        },
        { 
          episode_title: 'The Dumpling Paradox',
          season: 1,
          episode_number: 7,
          episode_length: '21:33 min',
          release_date: 'November 5, 2007',
          interesting_fact: 'First time Howard\'s mother is heard.',
          image: '/www.justwatch.com/images/backdrop/458881/s1440/the-big-bang-theory',
        },
        { 
          episode_title: 'The Grasshopper Experiment',
          season: 1,
          episode_number: 8,
          episode_length: '21:33 min',
          release_date: 'November 12, 2007',
          interesting_fact: 'With 9.32 millions viewers, The Grasshopper Experiment is the third most watched episode in the first season.',
          image: '/www.justwatch.com/images/backdrop/458881/s1440/the-big-bang-theory',
        },
        { 
          episode_title: 'The Cooper-Hofstadter Polarization',
          season: 1,
          episode_number: 9,
          episode_length: '20:25 min',
          release_date: 'March 17, 2008',
          interesting_fact: '“Leonard\'s spherical chicken joke (which Penny doesn\'t get): "There\'s this farmer, and he has these chickens, but they won\'t lay any eggs. So, he calls a physicist to help. The physicist then does some calculations, and he says, um, I have a solution, but it only works with spherical chickens in a vacuum." This is a variation on other joke involving a spherical cow. The point is that physicists reduce a problem to its simplest form in order to make calculations more feasible, even though such simplification may hinder the model\'s application to reality. Physicists assume spherical bodies in order to simplify equations by taking advantage of spherical symmetry, which can reduce a three dimensional problem into a simpler one dimensional problem. Physicists assume vacuum conditions so they can neglect possible interactions with the environment, which also simplifies the problem. It has nothing to do with radiative heat transfer or the pressure differential across the surface.',
          image: '/www.justwatch.com/images/backdrop/458881/s1440/the-big-bang-theory',
        },
        { 
          episode_title: 'The Loobenfeld Decay',
          season: 1,
          episode_number: 10,
          episode_length: '21:00 min',
          release_date: 'March 24, 2008',
          interesting_fact: 'This episode is the first time that Sheldon\'s trademark knock turns up, when he knocks on Leonard\'s bedroom door. There are two previous episodes in which Sheldon knocks on a door (actually Penny\'s door): S01E02 "The Big Bran Hypothesis" and S01E05 "The Hamburger Postulate", but in both he knocks \'normally\'."',
          image: '/www.justwatch.com/images/backdrop/458881/s1440/the-big-bang-theory',
        },
        { 
          episode_title: 'The Pancake Batter Anomaly',
          season: 1,
          episode_number: 11,
          episode_length: '22:00 min',
          release_date: 'March 31, 2008',
          interesting_fact: 'Code Milky Green is a code for when Sheldon is sick.',
          image: '/www.justwatch.com/images/backdrop/458881/s1440/the-big-bang-theory',
        },
        { 
          episode_title: 'The Jerusalem Duality',
          season: 1,
          episode_number: 12,
          episode_length: '22:00 min',
          release_date: 'March 14, 2008',
          interesting_fact: 'When Sheldon proposes his idea for the second wailing wall at the party, he is talking to "Professor Goldfarb". In the Hamburger Postulate, Leonard and Sheldon are discussing what Penny meant when she said, "You\'d make a cute couple". Sheldon replies with "An alternate, though somewhat less likely interpretation is that you could manufacture one. As in, \'Oh, look, Leonard and Leslie made Mr. and Mrs. Goldfarb! Aren\'t they adorable?’".',
          image: '/www.justwatch.com/images/backdrop/458881/s1440/the-big-bang-theory',
        },
        { 
          episode_title: 'The Bat Jar Conjecture',
          season: 1,
          episode_number: 13,
          episode_length: '22:00 min',
          release_date: 'April 21, 2008',
          interesting_fact: 'Sheldon designs uniforms that are emblazoned with the initials "AA", which he designed to mean "Army Ants", though Leonard points out it could imply something else (likely implying "Alcoholics Anonymous"), though Sheldon misses the point and guesses "Anodized Aluminum" as the next most likely acronym expansion.',
          image: '/www.justwatch.com/images/backdrop/458881/s1440/the-big-bang-theory',
        },
        { 
          episode_title: 'The Nerdvana Annihilation',
          season: 1,
          episode_number: 14,
          episode_length: '20:00 min',
          release_date: 'April 28, 2008',
          interesting_fact: 'The date on the time machine during Sheldon\'s (first) dream is April 28, the same date that this episode first aired.',
          image: '/www.justwatch.com/images/backdrop/458881/s1440/the-big-bang-theory',
        },
        { 
          episode_title: 'The Pork Chop Indeterminacy',
          season: 1,
          episode_number: 15,
          episode_length: '22:00 min',
          release_date: 'May 5, 2008',
          interesting_fact: 'The Wii that Howard and Leonard are using does not have holes to connect Game Cube controllers.',
          image: '/www.justwatch.com/images/backdrop/458881/s1440/the-big-bang-theory',
        },
        { 
          episode_title: 'The Peanut Reaction',
          season: 1,
          episode_number: 16,
          episode_length: '20:00 min',
          release_date: 'May 12, 2008',
          interesting_fact: 'According to Penny, Sheldon is a Taurus.',
          image: '/www.justwatch.com/images/backdrop/458881/s1440/the-big-bang-theory',
        },
        { 
          episode_title: 'The Tangerine Factor',
          season: 1,
          episode_number: 17,
          episode_length: '20:00 min',
          release_date: 'May 19, 2008',
          interesting_fact: 'Sheldon is correct in stating that light years are a measure of distance, not time.',
          image: '/www.justwatch.com/images/backdrop/458881/s1440/the-big-bang-theory',
        },
      ]));
};
