
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('description').del()
    .then(() =>
      // Inserts seed entries
      knex('description').insert([
        {
          description: 'After an unsuccessful visit to the high-IQ sperm bank, Dr. Leonard Hofstadter and Dr. Sheldon Cooper return home to find aspiring actress Penny is their new neighbor across the hall from their apartment. Sheldon thinks Leonard, who is immediately interested in her, is chasing a dream he will never catch. Leonard invites Penny to his and Sheldon\'s apartment for Indian food, where she asks to use their shower since hers is broken. While wrapped in a towel, she gets to meet their visiting friends Howard Wolowitz, a wannabe ladies\' man who tries to hit on her, and Rajesh Koothrappali, who is unable to speak to her as he suffers from selective mutism in the presence of women. Leonard is so infatuated with Penny that, after helping her use their shower, he agrees to retrieve her TV from her ex-boyfriend Kurt. However, Kurt\'s physical superiority overwhelms Leonard\'s and Sheldon\'s combined IQ of 360, and they return without pants or TV. Penny, feeling bad, offers to take the guys out to dinner, initiating a friendship with them.',
          episode_id: 1
        },
        {
          description: 'When Sheldon and Leonard drop off a box of flat pack furniture that came for Penny, Sheldon is deeply disturbed at how messy and disorganized her apartment is. Later that night, while Penny sleeps, the obsessive-compulsive Sheldon, unable to sleep, sneaks into her apartment to organize and clean it. Leonard finds out and reluctantly helps him. The next morning, Penny is furious to discover they had been in her apartment. Sheldon tries to apologize to Penny but fails by remarking that Leonard is a "gentle and thorough lover". Later, Penny encounters Raj in the hallway. Though he cannot talk to Penny, she calms down whilst telling him about the issue, reasoning the guys were just trying to help her, and hugs Raj. Then Leonard apologizes, prompting Penny to forgive and hug him.',
          episode_id: 2
        },
        {
          description: 'When he sees Penny kissing a man in front of her apartment door, Leonard is devastated that she has "rejected" him. The guys persuade him to date someone at work, so he approaches fellow scientist Leslie Winkle. In an experiment to strip the usual dating procedure to its essentials, she suggests fast forwarding to a kiss. She finds their kiss good but unexciting, so she turns him down. As Leonard becomes more depressed, thinking of buying a cat (hypoallergenic in view of Sheldon\'s asthma - though in later episodes Leonard is the one with asthma), Sheldon points out Leonard was not actually rejected by Penny as he never asked her out, so Leonard asks her out to dinner. As she misinterprets this as an invitation to hang out with all the guys, he devises reasons for their absence from the date. Penny says the man Leonard saw was not her boyfriend: casual weekend sex helps her get over relationships. Leonard, excited, regains his confidence, but he accidentally hurts himself and Penny has to take him home. In the end, Leonard does not find the courage to reveal his true feelings to Penny, though she suspected what he was up to.',
          episode_id: 3
        },
        {
          description: 'At the university Sheldon is fired from his job as a physicist after insulting his new boss Dr. Eric Gablehauser. Sheldon\'s change of circumstance triggers a downward spiral of depression in which he fails to improve scrambled eggs, develops luminous fish for nightlights, and weaves on a hand loom. Worried, Leonard calls Sheldon\'s mother, Mary Cooper. When she visits, the men realize she is the complete opposite of their expectations: she is sweet, down-to-earth, a devout Christian, and a loving and caring mother. Mary finally forces Sheldon to apologize, who is given his job back after she flirts with Dr. Gablehauser.',
          episode_id: 4
        },
        {
          description: 'The guys, eating at the Cheesecake Factory where Penny works, are approached by Leslie Winkle. She wants Leonard to play cello in her string quartet as the other players are uncomfortable near the current cellist who was possibly irradiated at work. After the quartet practise in Leonard and Sheldon\'s apartment, Leslie seduces Leonard for the night, making Sheldon so uneasy that he repeatedly asks Penny\'s advice. Penny later congratulates Leonard, who tries to figure out what she meant. Leonard decides to pursue a real relationship with Leslie rather than an imaginary one with Penny, but at her lab, Leslie makes it clear she is not interested in a relationship: she just needed him for a one-night stand to satisfy her sex drive - which is now satisfied until New Year. Leonard later tells Penny, who reassures him and walks away smiling.',
          episode_id: 5
        },
        {
          description: 'Penny invites the guys to her Halloween party. They at first decline as they do not dance, but accept when costumes are mentioned. At the party they have problems socializing: Sheldon is unable to explain his Doppler effect costume since none of Penny\'s friends are physicists or smart enough to understand it; Raj (dressed as Thor) cannot speak to women; Howard as Robin Hood is mistaken for Peter Pan; and Leonard (dressed as Frodo Baggins from The Lord of the Rings) is insecure. Penny\'s ex-boyfriend Kurt(underdressed as a very tall, muscular caveman) later shows up and aggressively confronts Leonard, causing him (and later Penny) to leave. Penny goes to check on Leonard and apologizes for Kurt\'s behavior. She is very upset, but Leonard tells her she is perfect, and they kiss, though Penny confesses she is drunk. They kiss again, in sight of Kurt, Leonard saying "That\'s how we roll at the Shire!" before locking his apartment door in panic. Meanwhile, Howard cannot find Raj, who is at home sleeping with party guest Cheryl who finds him to be a "very good listener".',
          episode_id: 6
        },
        {
          description: 'Penny\'s promiscuous acquaintance Christy from Omaha, Nebraska, "kind of family" since she slept with Penny\'s brother whilst engaged to her cousin, arrives to visit Penny indefinitely, and immediately beds Howard in Penny\'s apartment which the pair take over. Penny replaces Howard as a Halo 3 player and displays natural talent, to Sheldon\'s disbelief. To avoid the noisy "lovers", Penny sleeps on Leonard and Sheldon\'s couch that night. Next day, Howard invites Christy to move in with him (and his mother), taking up all his time. Distraught at the odd number in the group, Sheldon invites Penny to play Halo again, but she prefers to go dancing. The guys believe their group is falling apart and go to speak to Howard. There they hear Howard\'s mother arguing loudly with Christy, causing her to leave. Howard, single again, goes to play Halo with the guys, and the group is restored, completely ignoring Penny and her three attractive dancing friends who briefly appear at the door.',
          episode_id: 7
        },
        {
          description: 'Raj introduces his parents, Dr. V.M. Koothrappali and Mrs. Koothrappali, to his friends via webcam. However, Raj is overwhelmed when his parents try to arrange him a date with Lalita Gupta, a childhood friend and dental student, as he cannot talk to women. To Raj\'s annoyance Howard, using a fake Indian accent to impersonate Raj, phones Lalita to set up a date for them. Meanwhile, Penny takes up bar tending for some extra money. She practices mixing drinks with the guys, and they discover Raj is able to speak to women after drinking alcohol. They decide his date should be at Penny\'s restaurant so she and the guys can keep an eye on Raj\'s behavior when drinking. On his date, Raj becomes an obnoxious drunk. After Sheldon flatters Lalita with compliments comparing her to Princess Panchali, an Indian fairy tale princess, she takes him away for a meal, to Raj\'s horror. When Raj tries to explain all this to his parents, they are angry about his drinking. Leonard asks Sheldon if he plans to see Lalita again, but he replies that he already has a dentist.',
          episode_id: 8
        },
        {
          description: 'Leonard cleans up after an Internet experiment, and in the trash can he finds an invitation to him and Sheldon to present their joint research at an academic conference. Sheldon disapproves of presenting research in person, but Leonard defies him and goes alone. This causes a rift between the two which Penny tries to mend but accidentally makes worse. Sheldon appears at the conference and tries to discredit Leonard\'s presentation by attempting to "blow up" Leonard\'s head with his mind à la the movie Scanners, starting a physical altercation between the two. Howard films the fight on his cellphone and puts it on YouTube, but angers Penny by also posting a photo on Facebook of her sleeping on his shoulder during the presentation, entitled "Me and my girlfriend".',
          episode_id: 9
        },
        {
          description: 'Penny is given a part in the musical Rent, but after Leonard and Sheldon hear her off-key singing (Sheldon commenting, "if cats could sing, they\'d hate it too"), Leonard lies to avoid having to see her perform and hurt her feelings. Sheldon, worried that Leonard\'s lie was inadequate, devises an intricate lie about his nonexistent drug-addicted cousin "Leopold Houston" needing an intervention the night of the play). Sheldon is so obsessed with his lie\'s credibility that he has Toby Loobenfeld, a research assistant who double majored in Physics and Theatre, impersonate cousin "Leo" to convince Penny the lie is true. In the end, Leonard must still see the video of Penny\'s performance, and Penny and "Leo" start flirting.',
          episode_id: 10
        },
        {
          description: 'Penny returns from visiting family in Nebraska, but mentions while picking up mail from Leonard that most of her relatives became sick. Sheldon, a germophobe according to Leonard, freaks out and becomes sick, becoming demanding on top of his already obnoxious personality. Familiar with Sheldon being sick, Leonard and the guys hide from him at a Planet of the Apes series marathon, leaving Penny to care for Sheldon. However, Leonard breaks his glasses in the cinema and has to retrieve his spare pair from the apartment, piloted by Howard and Raj using a laptop, an endoscope, and a Bluetooth helmet cameraworn by the short-sighted Leonard. Penny intercepts him and abandons him to his fate with Sheldon. Leonard tries to escape, but runs into a wall and nearly knocks himself out. In the end, injured Leonard and sick Sheldon sit miserably on the couch.',
          episode_id: 11
        },
        {
          description: 'Sheldon becomes envious when he meets 15-year-old child prodigy Dennis Kim, who was invited to work at the university, and soon realizes that not only is Kim similar to himself (an obnoxious and arrogant child prodigy), but is even smarter than he. Sheldon loses faith in his own research and annoys his friends by criticizing their work more than ever and forcing his own contributions on them. Finding his physics work useless, he aims for the Nobel Peace Prize by attempting to solve all Middle East conflicts, but he annoys everyone, including a Jewish professor, with his proposal that an exact duplicate of Jerusalem be built in the Mexican desert. The others, tired of Sheldon\'s behavior, decide to distract Kim with girls of the same age. Their plan unexpectedly works at Kim\'s welcome party, and Kim leaves with a blonde 15-year-old. Sheldon resumes his research while the others are perplexed at how easily Kim was able to get a girl. In a park, the guys spot him drinking heavily and making out. They feel sorry at his demise, but the victorious Sheldon mocks him.',
          episode_id: 12
        },
        {
          description: 'The guys decide to compete in a physics bowl after the strong competitors drop out, but Sheldon\'s showboating is too much, and they eject him from the team. Sheldon, upset, vows to form his own team and compete against them. The guys, in need of a fourth member, ask Leslie Winkle. She at first declines, but accepts on hearing they are opposing Sheldon, who has often criticized her research and gender. The guys name themselves PMS (Perpetual Motion Squad, an unintentional pun on premenstrual syndrome). Sheldon\'s team is named AA (Army Ants, an unintentional pun on Alcoholics Anonymous), and comprises Sheldon (who forbids answers from his team mates), the 3rd floor janitor, the lunch lady, and her son (or possibly her butcher). PMS win when Sheldon, unable to answer the last question, refuses to accept the janitor\'s answer, which is actually correct: he explains that despite working as a janitor in America, he was a physicist in the former Soviet Union.',
          episode_id: 13
        },
        {
          description: 'In an online auction, Leonard buys a full-sized replica of the time machine from the 1960 film The Time Machine, believing it to be a miniature. The men\'s efforts to move the cumbersome object into the apartment cause Penny to lose a work shift, and she lashes out at them for their obsession with childish memorabilia. This upsets Leonard, who decides to sell all his collectibles. His friends try to dissuade him, but they also want his collectibles and argue over who should get what. Sheldon later accuses Penny of hypocrisy, pointing out her own love of such things as Hello Kitty or Care Bears. Penny apologizes to Leonard and dissuades him from abandoning the things he loves; he decides to keep his belongings. His hope of a relationship with her is thus very briefly renewed until her current boyfriend Mike appears and pulls her into her apartment. Sheldon later has nightmares of being attacked by Morlocks, and persuades Leonard to return the time machine replica.',
          episode_id: 14
        },
        {
          description: 'Sheldon introduces his twin sister Missy to the guys, and all are attracted to her. Raj decides to take part in a drug trial to cure his inability to talk to women, and Leonard insists Missy stay with them at the apartment. Predictably, the men all awkwardly flirt with her, so Penny comes to her rescue. Leonard, hoping for an advantage over Howard and Raj, convinces Sheldon he is Missy\'s guardian as concerns her choice of partner. Sheldon deems all three guys to be unsuitable for her. On learning of Sheldon\'s plan to find her a suitable mate, Missy confronts her brother, and after she kicks him in the groin he agrees she can date whoever she likes. She turns down Leonard, and then Howard, who fails to charm her with simple conjuring tricks. Finally Raj goes to talk to Missy, who shows interest in him, but the drug wears off and he is unable to speak to her, forcing Raj to leave defeated.',
          episode_id: 15
        },
        {
          description: 'Penny learns that Leonard has never had a birthday party, as his parents did not believe in celebrating anything other than achievements. She decides to throw him a surprise party, and blackmails Sheldon to join in by threatening to draw a smiley face on each of his mint condition comic books. However, on the day of the party, Penny discovers Sheldon has not yet bought a present, so she has to drive him to a computer store to buy one. Meanwhile, Howard has the task of keeping Leonard out of his apartment before the party. Howard pretends to eat a peanut bar, to which he is allergic, so that Leonard will drive him to the emergency room. However, Sheldon\'s lack of focus at the computer store means Howard has to distract Leonard even longer, and he eventually actually eats the peanut bar, swelling up in a severe allergic reaction. After several hours at the hospital, Howard and Leonard arrive back at the apartment to find the party has ended, though Penny does kiss Leonard.',
          episode_id: 16
        },
        {
          description: 'Penny furiously breaks up with Mike after he posts details of their sex life on his blog, while Sheldon, determined to prove that the Chinese restaurant uses oranges instead of tangerines in their "Tangerine chicken", asks Howard to teach him Mandarin. When Penny laments her choice of men, Leonard awkwardly asks her out. After a few days, both worry that this relationship could ruin their friendship, and each seeks Sheldon\'s advice. Sheldon uses the "Schrödinger\'s cat" thought experiment to explain that the date has both "good" and "bad" possible outcomes, and the only way to determine which outcome is to go on the date. When Leonard arrives to pick up Penny, he mentions the thought experiment and kisses her passionately. She concludes that "the cat is alive" and they leave for dinner. Leonard and Penny go to the Chinese restaurant, but they leave before entering on seeing Sheldon arguing with the owner in Mandarin, and doing it very badly, disturbing the patrons.',
          episode_id: 17
        },
      ]));
};
